// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/logs/logs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_api_proto_logs_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logs_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_logs_logs_proto_rawDescGZIP(), []int{0}
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*UserLogInfo         `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_api_proto_logs_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logs_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_logs_logs_proto_rawDescGZIP(), []int{1}
}

func (x *GetLogsResponse) GetInfo() []*UserLogInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UserLogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	LastUrl       string                 `protobuf:"bytes,2,opt,name=last_url,json=lastUrl,proto3" json:"last_url,omitempty"`
	Usages        int32                  `protobuf:"varint,3,opt,name=usages,proto3" json:"usages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogInfo) Reset() {
	*x = UserLogInfo{}
	mi := &file_api_proto_logs_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogInfo) ProtoMessage() {}

func (x *UserLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logs_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogInfo.ProtoReflect.Descriptor instead.
func (*UserLogInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_logs_logs_proto_rawDescGZIP(), []int{2}
}

func (x *UserLogInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserLogInfo) GetLastUrl() string {
	if x != nil {
		return x.LastUrl
	}
	return ""
}

func (x *UserLogInfo) GetUsages() int32 {
	if x != nil {
		return x.Usages
	}
	return 0
}

var File_api_proto_logs_logs_proto protoreflect.FileDescriptor

const file_api_proto_logs_logs_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/logs/logs.proto\x12\x04logs\"\x10\n" +
	"\x0eGetLogsRequest\"8\n" +
	"\x0fGetLogsResponse\x12%\n" +
	"\x04info\x18\x01 \x03(\v2\x11.logs.UserLogInfoR\x04info\"P\n" +
	"\vUserLogInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x19\n" +
	"\blast_url\x18\x02 \x01(\tR\alastUrl\x12\x16\n" +
	"\x06usages\x18\x03 \x01(\x05R\x06usages2D\n" +
	"\n" +
	"LogService\x126\n" +
	"\aGetLogs\x12\x14.logs.GetLogsRequest\x1a\x15.logs.GetLogsResponseB2Z0github.com/nikitagrgv/movies/delivery/grpc/pb;pbb\x06proto3"

var (
	file_api_proto_logs_logs_proto_rawDescOnce sync.Once
	file_api_proto_logs_logs_proto_rawDescData []byte
)

func file_api_proto_logs_logs_proto_rawDescGZIP() []byte {
	file_api_proto_logs_logs_proto_rawDescOnce.Do(func() {
		file_api_proto_logs_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_logs_logs_proto_rawDesc), len(file_api_proto_logs_logs_proto_rawDesc)))
	})
	return file_api_proto_logs_logs_proto_rawDescData
}

var file_api_proto_logs_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_logs_logs_proto_goTypes = []any{
	(*GetLogsRequest)(nil),  // 0: logs.GetLogsRequest
	(*GetLogsResponse)(nil), // 1: logs.GetLogsResponse
	(*UserLogInfo)(nil),     // 2: logs.UserLogInfo
}
var file_api_proto_logs_logs_proto_depIdxs = []int32{
	2, // 0: logs.GetLogsResponse.info:type_name -> logs.UserLogInfo
	0, // 1: logs.LogService.GetLogs:input_type -> logs.GetLogsRequest
	1, // 2: logs.LogService.GetLogs:output_type -> logs.GetLogsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_logs_logs_proto_init() }
func file_api_proto_logs_logs_proto_init() {
	if File_api_proto_logs_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_logs_logs_proto_rawDesc), len(file_api_proto_logs_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_logs_logs_proto_goTypes,
		DependencyIndexes: file_api_proto_logs_logs_proto_depIdxs,
		MessageInfos:      file_api_proto_logs_logs_proto_msgTypes,
	}.Build()
	File_api_proto_logs_logs_proto = out.File
	file_api_proto_logs_logs_proto_goTypes = nil
	file_api_proto_logs_logs_proto_depIdxs = nil
}
