servers:
  - id: "vidnest"
    name: "Vidnest"
    movie_url_template: "https://vidnest.fun/movie/{id}"
    tv_show_url_template: "https://vidnest.fun/tv/{id}/{s}/{e}"
  - id: "vidsrcmov"
    name: "VidSrc.mov"
    movie_url_template: "https://vidsrc.mov/embed/movie/{id}"
    tv_show_url_template: "https://vidsrc.mov/embed/tv/{id}/{s}/{e}"
  - id: "vidsrcfyi"
    name: "VidSrc.fyi"
    movie_url_template: "https://vidsrc.fyi/embed/movie/{id}"
    tv_show_url_template: "https://vidsrc.fyi/embed/tv/{id}/{s}/{e}"
  - id: "vidrock"
    name: "VidRock"
    movie_url_template: "https://vidrock.net/movie/{id}"
    tv_show_url_template: "https://vidrock.net/tv/{id}/{s}/{e}"
  - id: "vidking"
    name: "VidKing"
    movie_url_template: "https://www.vidking.net/embed/movie/{id}"
    tv_show_url_template: "https://www.vidking.net/embed/tv/{id}/{s}/{e}"
  - id: "vidlink"
    name: "VidLink"
    movie_url_template: "https://vidlink.pro/movie/{id}?autoplay=true&title=true"
    tv_show_url_template: "https://vidlink.pro/tv/{id}/{s}/{e}?autoplay=true&title=true"
  - id: "vidfast"
    name: "VidFast"
    movie_url_template: "https://vidfast.pro/movie/{id}?autoPlay=true"
    tv_show_url_template: "https://vidfast.pro/tv/{id}/{s}/{e}?autoPlay=true"
  - id: "vidup"
    name: "VidUp"
    movie_url_template: "https://vidup.to/movie/{id}?autoPlay=true"
    tv_show_url_template: "https://vidup.to/tv/{id}/{s}/{e}?autoPlay=true"
  - id: "videasy"
    name: "VidEasy"
    movie_url_template: "https://player.videasy.net/movie/{id}"
    tv_show_url_template: "https://player.videasy.net/tv/{id}/{s}/{e}"
  - id: "111movies"
    name: "111movies"
    movie_url_template: "https://111movies.com/movie/{id}"
    tv_show_url_template: "https://111movies.com/tv/{id}/{s}/{e}"
  - id: "2embed"
    name: "2embed"
    movie_url_template: "https://www.2embed.cc/embedmovie/{id}"
    tv_show_url_template: "https://www.2embed.cc/embedtv/{id}&s={s}&e={e}"
  - id: "multiembed"
    name: "Multiembed"
    movie_url_template: ""
    tv_show_url_template: "https://multiembed.mov/?video_id={id}&tmdb=1&s={s}&e={e}"
  - id: "superflixapi"
    name: "SuperFlixAPI"
    movie_url_template: "https://superflixapi.co/movie/{id}"
    tv_show_url_template: "https://superflixapi.co/serie/{id}/{s}/{e}"
  - id: "peachify"
    name: "Peachify"
    movie_url_template: "https://peachify.top/embed/movie/{id}"
    tv_show_url_template: "https://peachify.top/embed/tv/{id}/{s}/{e}"
  - id: "test"
    name: "Test"
    movie_url_template: "https://example.com/movie/{id}"
    tv_show_url_template: "https://example.com/tv/{id}/{s}/{e}"
